
export const SET_NOT_DISTRIBUTED_SHIPS = 'SET_NOT_DISTRIBUTED_SHIPS';
export const ADD_PLAYER_SHIP = 'ADD_PLAYER_SHIP';
export const UPDATE_PLAYER_SHIP = 'UPDATE_PLAYER_SHIP';
export const SET_CURRENT = 'SET_CURRENT';
export const ADD_SHOT_TO_MAP = 'ADD_SHOT_TO_MAP';
export const ADD_OPPONENT_SHOT_TO_MAP = 'ADD_OPPONENT_SHOT_TO_MAP';
export const ASSIGN_SHOOTER = 'ASSIGN_SHOOTER';
export const RESET_STATE = 'RESET_STATE';
export const SET_VOLUME = 'SET_VOLUME';







export const SET_ROOM_SETTINGS = 'SET_ROOM_SETTINGS';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_LAST_SUCCESS_GAME_STATUS = 'SET_LAST_SUCCESS_GAME_STATUS';
export const PLAYER_MOVE = 'PLAYER_MOVE';
export const OPPONENT_MOVE = 'OPPONENT_MOVE';
export const CLEAR_MOVES = 'CLEAR_MOVES';
export const SET_WIN = 'SET_WIN';

export const INCREASE_PLAYER_WINS_COUNTER = 'INCREASE_PLAYER_WINS_COUNTER';
export const INCREASE_OPPONENT_WINS_COUNTER = 'INCREASE_OPPONENT_WINS_COUNTER';
export const PUSH_MESSAGES_ARCHIVE = 'PUSH_MESSAGES_ARCHIVE';
export const CLEAR_MESSAGES_ARCHIVE = 'CLEAR_MESSAGES_ARCHIVE';
export const PUSH_MATCHES_ARCHIVE = 'PUSH_MATCHES_ARCHIVE';
export const CLEAR_MATCHES_ARCHIVE = 'CLEAR_MATCHES_ARCHIVE';
export const RESTORE_MATCHES_ARCHIVE = 'RESTORE_MATCHES_ARCHIVE';


