
export const SET_ROOM_SETTINGS = 'SET_ROOM_SETTINGS';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const SET_NOT_DISTRIBUTED_SHIPS = 'SET_NOT_DISTRIBUTED_SHIPS';
export const ADD_PLAYER_SHIP = 'ADD_PLAYER_SHIP';
export const UPDATE_PLAYER_SHIP = 'UPDATE_PLAYER_SHIP';
export const SET_CURRENT = 'SET_CURRENT';
export const ADD_SHOT_TO_MAP = 'ADD_SHOT_TO_MAP';
export const ADD_OPPONENT_SHOT_TO_MAP = 'ADD_OPPONENT_SHOT_TO_MAP';
export const ASSIGN_SHOOTER = 'ASSIGN_SHOOTER';
export const RESET_STATE = 'RESET_STATE';
export const SET_VOLUME = 'SET_VOLUME';
export const TOGGLE_OPPONENT_DISCONNECTED_MODAL = 'TOGGLE_OPPONENT_DISCONNECTED_MODAL';
export const SET_ROOM_DESTROY_DEADLINE = 'SET_ROOM_DESTROY_DEADLINE';
export const UPDATE_ONLINE_ROOMS = 'UPDATE_ONLINE_ROOM';











